# This DDL file is used to create the database schema for the bundle persistence manager
# in Apache Jackrabbit when using HSQLDB as the underlying database.
#

create table ${schemaObjectPrefix}BUNDLE (NODE_ID binary(64) not null, BUNDLE_DATA longvarbinary not null, primary key (NODE_ID));
create table ${schemaObjectPrefix}REFS (NODE_ID binary(64) not null, REFS_DATA longvarbinary not null, primary key (NODE_ID));
create table ${schemaObjectPrefix}BINVAL (BINVAL_ID varchar(64) not null, BINVAL_DATA longvarbinary not null, primary key (BINVAL_ID));
create table ${schemaObjectPrefix}NAMES (ID integer generated by default as identity, NAME varchar(255) not null, primary key (ID));
create unique index ${schemaObjectPrefix}NAMES_IDX on ${schemaObjectPrefix}NAMES (NAME);
