//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.10 at 09:40:29 AM EST 
//


package org.pentaho.platform.repository2.unified.ExportManifest;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExportManifestDto complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ExportManifestDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ManifestInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="exportDate" type="{http://www.w3.org/2001/XMLSchema}string" default="{date}" />
 *                 &lt;attribute name="exportBy" type="{http://www.w3.org/2001/XMLSchema}string" default="{user}" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ExportManifestEntity" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ExportManifestProperty" type="{http://www.example.org/ExportManifest/}ExportManifestPropertyDto" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="path">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;minLength value="1"/>
 *                       &lt;maxLength value="255"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportManifestDto", propOrder = {
    "manifestInformation",
    "exportManifestEntity"
})
public class ExportManifestDto {

    @XmlElement(name = "ManifestInformation", required = true)
    protected ExportManifestDto.ManifestInformation manifestInformation;
    @XmlElement(name = "ExportManifestEntity", required = true)
    protected List<ExportManifestDto.ExportManifestEntity> exportManifestEntity;

    /**
     * Gets the value of the manifestInformation property.
     * 
     * @return
     *     possible object is
     *     {@link ExportManifestDto.ManifestInformation }
     *     
     */
    public ExportManifestDto.ManifestInformation getManifestInformation() {
        return manifestInformation;
    }

    /**
     * Sets the value of the manifestInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportManifestDto.ManifestInformation }
     *     
     */
    public void setManifestInformation(ExportManifestDto.ManifestInformation value) {
        this.manifestInformation = value;
    }

    /**
     * Gets the value of the exportManifestEntity property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the exportManifestEntity property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExportManifestEntity().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExportManifestDto.ExportManifestEntity }
     * 
     * 
     */
    public List<ExportManifestDto.ExportManifestEntity> getExportManifestEntity() {
        if (exportManifestEntity == null) {
            exportManifestEntity = new ArrayList<ExportManifestDto.ExportManifestEntity>();
        }
        return this.exportManifestEntity;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ExportManifestProperty" type="{http://www.example.org/ExportManifest/}ExportManifestPropertyDto" maxOccurs="unbounded"/>
     *       &lt;/sequence>
     *       &lt;attribute name="path">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;minLength value="1"/>
     *             &lt;maxLength value="255"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "exportManifestProperty"
    })
    public static class ExportManifestEntity {

        @XmlElement(name = "ExportManifestProperty", required = true)
        protected List<ExportManifestPropertyDto> exportManifestProperty;
        @XmlAttribute
        protected String path;

        /**
         * Gets the value of the exportManifestProperty property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the exportManifestProperty property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getExportManifestProperty().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ExportManifestPropertyDto }
         * 
         * 
         */
        public List<ExportManifestPropertyDto> getExportManifestProperty() {
            if (exportManifestProperty == null) {
                exportManifestProperty = new ArrayList<ExportManifestPropertyDto>();
            }
            return this.exportManifestProperty;
        }

        /**
         * Gets the value of the path property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPath() {
            return path;
        }

        /**
         * Sets the value of the path property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPath(String value) {
            this.path = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="exportDate" type="{http://www.w3.org/2001/XMLSchema}string" default="{date}" />
     *       &lt;attribute name="exportBy" type="{http://www.w3.org/2001/XMLSchema}string" default="{user}" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class ManifestInformation {

        @XmlAttribute
        protected String exportDate;
        @XmlAttribute
        protected String exportBy;

        /**
         * Gets the value of the exportDate property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExportDate() {
            if (exportDate == null) {
                return "{date}";
            } else {
                return exportDate;
            }
        }

        /**
         * Sets the value of the exportDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExportDate(String value) {
            this.exportDate = value;
        }

        /**
         * Gets the value of the exportBy property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getExportBy() {
            if (exportBy == null) {
                return "{user}";
            } else {
                return exportBy;
            }
        }

        /**
         * Sets the value of the exportBy property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setExportBy(String value) {
            this.exportBy = value;
        }

    }

}
