//
/*!
 * This program is free software; you can redistribute it and/or modify it under the
 * terms of the GNU Lesser General Public License, version 2.1 as published by the Free Software
 * Foundation.
 *
 * You should have received a copy of the GNU Lesser General Public License along with this
 * program; if not, you can obtain a copy at http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html
 * or from the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See the GNU Lesser General Public License for more details.
 *
 * Copyright (c) 2002-2013 Pentaho Corporation..  All rights reserved.
 */

// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.02.13 at 12:51:52 PM EST 
//


package org.pentaho.platform.plugin.services.importer.mimeType.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MimeTypeDefinitionDto complex type.
 * <p/>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p/>
 * <pre>
 * &lt;complexType name="MimeTypeDefinitionDto">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="extension" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mimeType" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hidden" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="locale" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="converter" type="{http://www.w3.org/2001/XMLSchema}string" default="streamConverter" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType ( XmlAccessType.FIELD )
@XmlType ( name = "MimeTypeDefinitionDto", propOrder = {
    "extension"
    } )
public class MimeTypeDefinitionDto {

  @XmlElement ( required = true )
  protected List<String> extension;
  @XmlAttribute ( name = "mimeType", required = true )
  protected String mimeType;
  @XmlAttribute ( name = "hidden" )
  protected Boolean hidden;
  @XmlAttribute ( name = "locale" )
  protected Boolean locale;
  @XmlAttribute ( name = "converter" )
  protected String converter;

  /**
   * Gets the value of the extension property.
   * <p/>
   * <p/>
   * This accessor method returns a reference to the live list,
   * not a snapshot. Therefore any modification you make to the
   * returned list will be present inside the JAXB object.
   * This is why there is not a <CODE>set</CODE> method for the extension property.
   * <p/>
   * <p/>
   * For example, to add a new item, do as follows:
   * <pre>
   *    getExtension().add(newItem);
   * </pre>
   * <p/>
   * <p/>
   * <p/>
   * Objects of the following type(s) are allowed in the list
   * {@link String }
   */
  public List<String> getExtension() {
    if ( extension == null ) {
      extension = new ArrayList<String>();
    }
    return this.extension;
  }

  /**
   * Gets the value of the mimeType property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getMimeType() {
    return mimeType;
  }

  /**
   * Sets the value of the mimeType property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setMimeType( String value ) {
    this.mimeType = value;
  }

  /**
   * Gets the value of the hidden property.
   *
   * @return possible object is
   * {@link Boolean }
   */
  public boolean isHidden() {
    if ( hidden == null ) {
      return false;
    } else {
      return hidden;
    }
  }

  /**
   * Sets the value of the hidden property.
   *
   * @param value allowed object is
   *              {@link Boolean }
   */
  public void setHidden( Boolean value ) {
    this.hidden = value;
  }

  /**
   * Gets the value of the locale property.
   *
   * @return possible object is
   * {@link Boolean }
   */
  public boolean isLocale() {
    if ( locale == null ) {
      return false;
    } else {
      return locale;
    }
  }

  /**
   * Sets the value of the locale property.
   *
   * @param value allowed object is
   *              {@link Boolean }
   */
  public void setLocale( Boolean value ) {
    this.locale = value;
  }

  /**
   * Gets the value of the converter property.
   *
   * @return possible object is
   * {@link String }
   */
  public String getConverter() {
    if ( converter == null ) {
      return "streamConverter";
    } else {
      return converter;
    }
  }

  /**
   * Sets the value of the converter property.
   *
   * @param value allowed object is
   *              {@link String }
   */
  public void setConverter( String value ) {
    this.converter = value;
  }

}
