#### Plugin Configuration should go here.  This file is used to override any default plugin configuration settings.

### webttle-pdc-api-plugin

## Mandatory settings for webttle-pdc-api-plugin - Update before starting the server
pdcapi.url=
pdcapi.username=
pdcapi.password=
pdcapi.encryptionKey=

