/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2029-07-20
 ******************************************************************************/


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 11:25:28 AM EDT 
//

package org.pentaho.platform.plugin.services.importexport.exportManifest.bindings;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for incrementalRecurrence complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="incrementalRecurrence">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="increment" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="startingValue" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "incrementalRecurrence", propOrder = { "increment", "startingValue" } )
public class IncrementalRecurrence {

  protected Integer increment;
  protected Integer startingValue;

  /**
   * Gets the value of the increment property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getIncrement() {
    return increment;
  }

  /**
   * Sets the value of the increment property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setIncrement( Integer value ) {
    this.increment = value;
  }

  /**
   * Gets the value of the startingValue property.
   * 
   * @return possible object is {@link Integer }
   * 
   */
  public Integer getStartingValue() {
    return startingValue;
  }

  /**
   * Sets the value of the startingValue property.
   * 
   * @param value
   *          allowed object is {@link Integer }
   * 
   */
  public void setStartingValue( Integer value ) {
    this.startingValue = value;
  }

}
