/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2029-07-20
 ******************************************************************************/


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 11:25:28 AM EDT 
//

package org.pentaho.platform.plugin.services.importexport.exportManifest.bindings;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;

/**
 * <p>
 * Java class for jobTrigger complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="jobTrigger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="cronString" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="duration" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="endTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="startTime" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="uiPassParam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "jobTrigger", propOrder = { "cronString", "duration", "endTime", "startTime", "uiPassParam", "startHour", "startMin", "startAmPm", "startYear", "startMonth", "startDay", "timeZone" } )
@XmlSeeAlso( { SimpleJobTrigger.class, CronJobTrigger.class, ComplexJobTrigger.class } )
public abstract class JobTrigger {

  protected String cronString;
  protected long duration;
  @XmlSchemaType( name = "dateTime" )
  protected XMLGregorianCalendar endTime;
  @XmlSchemaType( name = "dateTime" )
  protected XMLGregorianCalendar startTime;
  protected String uiPassParam;

  protected int startMin = -1;
  protected int startHour = -1;
  protected int startYear = -1;
  protected int startMonth = -1;
  protected int startDay = -1;
  protected int startAmPm = -1;
  protected String timeZone;

  /**
   * Gets the value of the cronString property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getCronString() {
    return cronString;
  }

  /**
   * Sets the value of the cronString property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setCronString( String value ) {
    this.cronString = value;
  }

  /**
   * Gets the value of the duration property.
   * 
   */
  public long getDuration() {
    return duration;
  }

  /**
   * Sets the value of the duration property.
   * 
   */
  public void setDuration( long value ) {
    this.duration = value;
  }

  /**
   * Gets the value of the endTime property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getEndTime() {
    return endTime;
  }

  /**
   * Sets the value of the endTime property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setEndTime( XMLGregorianCalendar value ) {
    this.endTime = value;
  }

  /**
   * Gets the value of the startTime property.
   * 
   * @return possible object is {@link XMLGregorianCalendar }
   * 
   */
  public XMLGregorianCalendar getStartTime() {
    return startTime;
  }

  /**
   * Sets the value of the startTime property.
   * 
   * @param value
   *          allowed object is {@link XMLGregorianCalendar }
   * 
   */
  public void setStartTime( XMLGregorianCalendar value ) {
    this.startTime = value;
  }

  /**
   * Gets the value of the uiPassParam property.
   * 
   * @return possible object is {@link String }
   * 
   */
  public String getUiPassParam() {
    return uiPassParam;
  }

  /**
   * Sets the value of the uiPassParam property.
   * 
   * @param value
   *          allowed object is {@link String }
   * 
   */
  public void setUiPassParam( String value ) {
    this.uiPassParam = value;
  }

  public int getStartHour() {
    return startHour;
  }

  public void setStartHour( int startHour ) {
    this.startHour = startHour;
  }

  public int getStartMin() {
    return startMin;
  }

  public void setStartMin( int startMin ) {
    this.startMin = startMin;
  }

  public int getStartYear() {
    return startYear;
  }

  public void setStartYear( int startYear ) {
    this.startYear = startYear;
  }

  public int getStartMonth() {
    return startMonth;
  }

  public void setStartMonth( int startMonth ) {
    this.startMonth = startMonth;
  }

  public int getStartDay() {
    return startDay;
  }

  public void setStartDay( int startDay ) {
    this.startDay = startDay;
  }

  public int getStartAmPm() {
    return startAmPm;
  }

  public void setStartAmPm( int startAmPm ) {
    this.startAmPm = startAmPm;
  }

  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone( String timeZone ) {
    this.timeZone = timeZone;
  }

}
