/*! ******************************************************************************
 *
 * Pentaho
 *
 * Copyright (C) 2024 by Hitachi Vantara, LLC : http://www.pentaho.com
 *
 * Use of this software is governed by the Business Source License included
 * in the LICENSE.TXT file.
 *
 * Change Date: 2029-07-20
 ******************************************************************************/


//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 11:25:28 AM EDT 
//

package org.pentaho.platform.plugin.services.importexport.exportManifest.bindings;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for qualifiedDayOfWeek complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="qualifiedDayOfWeek">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="dayOfWeek" type="{http://www.pentaho.com/schema/}dayOfWeek" minOccurs="0"/>
 *         &lt;element name="qualifier" type="{http://www.pentaho.com/schema/}dayOfWeekQualifier" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType( XmlAccessType.FIELD )
@XmlType( name = "qualifiedDayOfWeek", propOrder = { "dayOfWeek", "qualifier" } )
public class QualifiedDayOfWeek {

  protected DayOfWeek dayOfWeek;
  protected DayOfWeekQualifier qualifier;

  /**
   * Gets the value of the dayOfWeek property.
   * 
   * @return possible object is {@link DayOfWeek }
   * 
   */
  public DayOfWeek getDayOfWeek() {
    return dayOfWeek;
  }

  /**
   * Sets the value of the dayOfWeek property.
   * 
   * @param value
   *          allowed object is {@link DayOfWeek }
   * 
   */
  public void setDayOfWeek( DayOfWeek value ) {
    this.dayOfWeek = value;
  }

  /**
   * Gets the value of the qualifier property.
   * 
   * @return possible object is {@link DayOfWeekQualifier }
   * 
   */
  public DayOfWeekQualifier getQualifier() {
    return qualifier;
  }

  /**
   * Sets the value of the qualifier property.
   * 
   * @param value
   *          allowed object is {@link DayOfWeekQualifier }
   * 
   */
  public void setQualifier( DayOfWeekQualifier value ) {
    this.qualifier = value;
  }

}
