//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.25 at 11:25:28 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.pentaho.com/schema/")
package org.pentaho.platform.plugin.services.importexport.exportManifest.bindings;
