-- Script for migrating from quarts 1.5.2 to quartz 1.7.x

\connect quartz pentaho_user

begin;

ALTER TABLE qrtz_job_details 
    ALTER JOB_NAME       TYPE VARCHAR(200), 
    ALTER JOB_GROUP      TYPE VARCHAR(200), 
    ALTER DESCRIPTION    TYPE VARCHAR(250), 
    ALTER JOB_CLASS_NAME TYPE VARCHAR(250);

ALTER TABLE qrtz_job_listeners 
    ALTER JOB_NAME     TYPE VARCHAR(200), 
    ALTER JOB_GROUP    TYPE VARCHAR(200), 
    ALTER JOB_LISTENER TYPE VARCHAR(200);
    
ALTER TABLE qrtz_triggers
    ALTER TRIGGER_NAME  TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP TYPE VARCHAR(200),
    ALTER JOB_NAME      TYPE VARCHAR(200),
    ALTER JOB_GROUP     TYPE VARCHAR(200),
    ALTER DESCRIPTION   TYPE VARCHAR(250),
    ALTER CALENDAR_NAME TYPE VARCHAR(200),
    ADD COLUMN PRIORITY INTEGER NULL;
    
ALTER TABLE qrtz_simple_triggers
    ALTER TRIGGER_NAME    TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP   TYPE VARCHAR(200);
    
ALTER TABLE qrtz_cron_triggers
    ALTER TRIGGER_NAME    TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP   TYPE VARCHAR(200),
    ALTER CRON_EXPRESSION TYPE VARCHAR(200);
    
ALTER TABLE qrtz_blob_triggers
    ALTER TRIGGER_NAME  TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP TYPE VARCHAR(200);
    
ALTER TABLE qrtz_trigger_listeners
    ALTER TRIGGER_NAME     TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP    TYPE VARCHAR(200),
    ALTER TRIGGER_LISTENER TYPE VARCHAR(200);
    
ALTER TABLE qrtz_calendars
    ALTER CALENDAR_NAME TYPE VARCHAR(200);
    
ALTER TABLE qrtz_paused_trigger_grps
    ALTER TRIGGER_GROUP  TYPE VARCHAR(200);
    
ALTER TABLE qrtz_fired_triggers
    ALTER TRIGGER_NAME  TYPE VARCHAR(200),
    ALTER TRIGGER_GROUP TYPE VARCHAR(200),
    ALTER INSTANCE_NAME TYPE VARCHAR(200),
    ALTER JOB_NAME      TYPE VARCHAR(200),
    ALTER JOB_GROUP     TYPE VARCHAR(200),
    ADD COLUMN PRIORITY INTEGER NOT NULL;

ALTER TABLE qrtz_scheduler_state
    ALTER INSTANCE_NAME  TYPE VARCHAR(200),
    DROP COLUMN RECOVERER;

commit;
