//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 02:56:23 PM EDT 
//


package org.pentaho.platform.repository2.unified.exportManifest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for howOften complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="howOften">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="once" type="{http://www.pentaho.com/schema/}periodOnce"/>
 *         &lt;element name="period" type="{http://www.pentaho.com/schema/}periodic"/>
 *         &lt;element name="cron" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "howOften", propOrder = {
    "once",
    "period",
    "cron"
})
public class HowOften {

    protected PeriodOnce once;
    protected Periodic period;
    protected String cron;

    /**
     * Gets the value of the once property.
     * 
     * @return
     *     possible object is
     *     {@link PeriodOnce }
     *     
     */
    public PeriodOnce getOnce() {
        return once;
    }

    /**
     * Sets the value of the once property.
     * 
     * @param value
     *     allowed object is
     *     {@link PeriodOnce }
     *     
     */
    public void setOnce(PeriodOnce value) {
        this.once = value;
    }

    /**
     * Gets the value of the period property.
     * 
     * @return
     *     possible object is
     *     {@link Periodic }
     *     
     */
    public Periodic getPeriod() {
        return period;
    }

    /**
     * Sets the value of the period property.
     * 
     * @param value
     *     allowed object is
     *     {@link Periodic }
     *     
     */
    public void setPeriod(Periodic value) {
        this.period = value;
    }

    /**
     * Gets the value of the cron property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCron() {
        return cron;
    }

    /**
     * Sets the value of the cron property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCron(String value) {
        this.cron = value;
    }

}
