//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.01.11 at 01:58:33 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.example.org/ExportManifest/")
package org.pentaho.platform.repository2.unified.exportManifest.bindings;
