//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.18 at 02:56:23 PM EDT 
//


package org.pentaho.platform.repository2.unified.exportManifest.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for schedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="schedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="when" type="{http://www.pentaho.com/schema/}scheduleLifetime"/>
 *         &lt;element name="howOften" type="{http://www.pentaho.com/schema/}howOften"/>
 *         &lt;element name="file" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "schedule", propOrder = {
    "when",
    "howOften",
    "file"
})
public class Schedule {

    @XmlElement(required = true)
    protected ScheduleLifetime when;
    @XmlElement(required = true)
    protected HowOften howOften;
    @XmlElement(required = true)
    protected String file;

    /**
     * Gets the value of the when property.
     * 
     * @return
     *     possible object is
     *     {@link ScheduleLifetime }
     *     
     */
    public ScheduleLifetime getWhen() {
        return when;
    }

    /**
     * Sets the value of the when property.
     * 
     * @param value
     *     allowed object is
     *     {@link ScheduleLifetime }
     *     
     */
    public void setWhen(ScheduleLifetime value) {
        this.when = value;
    }

    /**
     * Gets the value of the howOften property.
     * 
     * @return
     *     possible object is
     *     {@link HowOften }
     *     
     */
    public HowOften getHowOften() {
        return howOften;
    }

    /**
     * Sets the value of the howOften property.
     * 
     * @param value
     *     allowed object is
     *     {@link HowOften }
     *     
     */
    public void setHowOften(HowOften value) {
        this.howOften = value;
    }

    /**
     * Gets the value of the file property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFile() {
        return file;
    }

    /**
     * Sets the value of the file property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFile(String value) {
        this.file = value;
    }

}
